### ISSUE TITLE
项目应用

### ISSUE THREAD

**Issue by zhengxinvip** [lvgithub/stick#10]
这个包是否可以应用再后台服务器向前台传递数据?后台服务器是express+nodejs  前端是vue开发

**Comment by lvgithub** [comment]
你前台用HTTP 不就好了吗？

**Comment by zhengxinvip** [comment]
是的  但是由于图片的大小和数量  因此想到定义一个传输的协议

**Comment by lvgithub** [comment]
那可以基于这个包来实现。包头+ 包体

**Comment by zhengxinvip** [comment]
好的  我尝试一下 谢谢你

**Comment by zhengxinvip** [comment]
如何是这样的话存在一个问题  我后台是nodejs 前台是vue  那我使用你这个包的时候 我的后台应该是当作发送方  前台当作服务端  那我是再前端和后端都安装这个包吗

**Comment by lvgithub** [comment]
不是的，你先补补基础知识吧。

**Comment by lvgithub** [comment]
这个包只支持服务端
