### ISSUE TITLE
有逻辑错误，收到正好长度的包时，没有emit事件

### ISSUE THREAD

**Issue by figozhu** [lvgithub/stick#12]
有逻辑错误，收到正好长度的包时，没有emit事件

要等到再来包，才emit

**Comment by figozhu** [comment]
> 提供下最小的demo代码。

长度字段是包的总长度？
还是整个包长度 - 长度字段字节数？

**Comment by lvgithub** [comment]
整个包长度 - 长度字段字节数

**Comment by lvgithub** [comment]
例如：[0x00, 0x02, 0x66, 0x66]  包头为两个字节：0x00 0x02 代表数据包body的长度2。 0x66 0x66 就是body了，长度为2。
