### ISSUE TITLE
stickpackage提供typescript支持

### ISSUE THREAD

**Issue by cevio** [lvgithub/stick#13]
感谢作者提供思路和源码，我已将此项目修改为ts支持，请参考[@nelts/tcp-stick](https://github.com/nelts/tcp-stick)。

不过也报一个问题：

请看我readme.md 中 example处

```ts
// ...
client.write(data + '1');
```

这样写就有问题。您可以尝试下。

**Comment by cevio** [comment]
不好意思，是我自己写错了。抱歉。没有问题。

**Comment by lvgithub** [comment]
没事，欢迎star
