### ISSUE TITLE
包头的问题

### ISSUE THREAD

**Issue by Ants-double** [lvgithub/stick#3]
我的包头是8个字节，前四个是包的类别，后四个是长度，要怎么用呢，我看你的好像是默认为分包头和内容。我如果指定包头为8 ，那长度就会有错啊，请指教，新手。

**Comment by lvgithub** [comment]
你是包头对于这个库来说，其实也属于内容。你把整个的长度算下，传输获取后，再解析你自定义呢包头。

**Comment by Ants-double** [comment]
长度是变化的，不是固定的，我要接收到一条流后才可以知道 啊

**Comment by Ants-double** [comment]
ok ,i change some code to fix my code.thankyou.

**Comment by lvgithub** [comment]
方便把你的代码贴一下吗，我看下怎么修改，或者我把这个库升级成更灵活一些

**Comment by lvgithub** [comment]
长度变化的是正常的，可以动态计算后下进行发送

**Comment by lvgithub** [comment]
下一个版本我准备支持直接发送对象的形式，封装组装包长度的细节

**Comment by HelloKevinTian** [comment]
建议对自定义包头有更详细的文档和支持。比如一般协议的包头：msgLength+protoId+msgContent

**Comment by lvgithub** [comment]
可以有

**Comment by greenteaone** [comment]
疑问满满的，为什么我把数据打印出来发现，只是数据转发了一下，加了长度，其他都没有变化呢？没有看到实现解决粘连啊？是不是我用错了？

**Comment by lvgithub** [comment]
> 疑问满满的，为什么我把数据打印出来发现，只是数据转发了一下，加了长度，其他都没有变化呢？没有看到实现解决粘连啊？是不是我用错了？

贴下你用的代码

**Comment by zhengxinvip** [comment]
> ok ,i change some code to fix my code.thankyou.

您好，我遇到和您一样的问题，请问可以给一下指点吗 谢谢

**Comment by lvgithub** [comment]
> > ok ,i change some code to fix my code.thankyou.
> 
> 您好，我遇到和您一样的问题，请问可以给一下指点吗 谢谢

说下你的打包方式，或者你看example里面的示例打包

**Comment by zhengxinvip** [comment]
> > > ok ,i change some code to fix my code.thankyou.
> > 
> > 
> > 您好，我遇到和您一样的问题，请问可以给一下指点吗 谢谢
> 
> 说下你的打包方式，或者你看example里面的示例打包

您好，您的代码包头长度设置为2字节或四字节，如果我想自定义传输协议，将包头定义为校验码+命令参数（1---传输消息 2----传输图片）+包头长度，我如何扩展，初学者，希望给予指点，谢谢。

**Comment by zhengxinvip** [comment]
包头长度应修改为包体长度

**Comment by zhengxinvip** [comment]
您这里的包头的内容指的是包体的长度是吗

**Comment by lvgithub** [comment]
是的
