### ISSUE TITLE
core.js长度拷贝问题？

### ISSUE THREAD

**Issue by SeaUT** [lvgithub/stick#5]
![image](https://user-images.githubusercontent.com/18068516/45358914-9242ba00-b5fd-11e8-985f-16ff09a044bb.png)

拷贝时使用的buffLastCanReadLen长度有问题吧？

**Comment by lvgithub** [comment]
什么问题？

**Comment by SeaUT** [comment]
个人理解193行copy最后一个参数的边界有问题。  应该为：   _buffer.copy(headBuffer, 0, _dataReadPosition, `buffLastCanReadLen + _dataReadPosition`);
或者_buffer.copy(headBuffer, 0, _dataReadPosition,  _bufferLength);``

**Comment by lvgithub** [comment]
确实有这个bug,你可以提交个pr

**Comment by SeaUT** [comment]
github不太会用  我就是需要用到  来学习下代码

**Comment by lvgithub** [comment]
已经修复

**Comment by SeaUT** [comment]
接触nodejs不久   代码很nice  收益颇多  谢谢
