### ISSUE TITLE
疑问满满的，为什么我把数据打印出来发现，只是数据转发了一下，加了长度，其他都没有变化呢？没有看到实现解决粘连啊？是不是我用错了？

### ISSUE THREAD

**Issue by greenteaone** [lvgithub/stick#7]
我的用法就是：
const Stick = require('stickpackage').stick;
stick = new Stick(48).setReadIntBE('16');  
stick.putMsg(data); //这里是放在sever里的 data事件里发送数据的，用putData事件接收不到数据，所以就用putMsg了

stick.onData(function (data) {
            console.log('receive data,length:' + data.length);
            console.log('receive data,contents:' + JSON.stringify(data));
            // console.log('receive data,contents:');
        });

**Comment by lvgithub** [comment]
server 端你接受到的数据是bytes 类型的，需要用putData. 
你这边问题，应该在你客户端发送消息的代码，应该使用的不对。你贴下client 部分

**Comment by lvgithub** [comment]
msgCenter.putMsg(msg) => 向消息中心推送字符串消息

**Comment by greenteaone** [comment]
msgCenter.putMsg(msg) => 向消息中心推送字符串消息
这个我也试过了，我的data打印出来就一条，但是putMsg以后就会一条数据会重复两遍，不知道为什么

**Comment by greenteaone** [comment]
putData要1万多个字节才能收到，这个不知道怎么解决？

**Comment by lvgithub** [comment]
putData要1万多个字节才能收到。 说明客户端的数据包，包头错了。你的客户端用法应该不对，贴下客户端的代码吧

**Comment by greenteaone** [comment]
var net = require('net');
const Stick = require('stickpackage').stick;
const MsgCenter = require('stickpackage').msgCenter
const msgCenter = new MsgCenter({
    bufferSize: 48,
    type: 16
});
const stick = new Stick(48).setReadIntBE('16');
var server = net.createServer(function (connection) {
    console.log('有TCP客户端连接进入');
    connection.on('end', function () {
        console.log('客户端连接断开');
    });
    connection.on("data", function (data) {
        //stick.putData(data);
        // msgCenter.putData(data);
        msgCenter.putMsg(data);
    })
    // stick.onData(function (data) {
    //     console.log('receive data,length:' + data.length);
    //     console.log('receive data,contents:' + JSON.stringify(data));
    //     // console.log('receive data,contents:');
    // });


    msgCenter.onMsgRecv(data => {
        console.log(`recv data length: ` + data.length);
        console.log(`recv data: ` + JSON.stringify(data))
    })

    connection.on("close", function (code, reason) {
        console.log("TCP关闭连接")
    });
    connection.on("error", function (error) {
        console.log("TCP异常关闭：", JSON.stringify(error))
    });
});

server.listen(1001, function (data) {
    console.log('TCP服务启动，监听1001');
});

**Comment by greenteaone** [comment]
方法都试过了，但是不行

**Comment by greenteaone** [comment]
我只负责接收数据

**Comment by lvgithub** [comment]
谁给你发的数据

**Comment by lvgithub** [comment]
包头错了：1112 --表示你的数据长度4370

**Comment by lvgithub** [comment]
示例： <Buffer 00 03 31 32 33> // 00 03 包长度  31 32 33 字符串123的ascii码

**Comment by greenteaone** [comment]
那就是我这个不能用你这个方法喽

**Comment by greenteaone** [comment]
因为我的包都是不带包头的

**Comment by lvgithub** [comment]
你们接收的是什么类型的数据？视频、消息？
